apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaadinlombokhashequals
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vaadinlombokhashequals
  template:
    metadata:
      labels:
        app: vaadinlombokhashequals
    spec:
      containers:
        - name: vaadinlombokhashequals
          image: vaadinlombokhashequals:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: '1'

---
apiVersion: v1
kind: Service
metadata:
  name: vaadinlombokhashequals-balancer
spec:
  selector:
    app: vaadinlombokhashequals
  ports:
    - protocol: TCP
      port: 8000 # The port to expose to the outside
      targetPort: 8080 # The port the application is running on in the pods
  type: LoadBalancer
  sessionAffinity: ClientIP
